model:
  in_channels: 30
  out_channels: 30
  embed_dim: 512
  expand: 4
  depth: 8
  patch_size: [7, 15] 
  img_height: 721
  img_width: 1440
  dt_ref: 6.0
  sde_mode: "sde"
  init_noise_scale: 0.0001
  max_growth_rate: 0.3
  ensemble_size: 4

data:
  input_dir: "/nfs/ERA5_data/data_norm"
  year_range: [2001, 2005]
  window_size: 10
  sampling_mode: "mix"

alignment:
  pretrained_ckpt: "./uniphy/ckpt/ckpt_final.pt"
  target_dt: 6.0
  max_rollout_steps: 4
  sub_steps: [1, 2, 3, 6]

train:
  batch_size: 1
  lr: 5.0e-5
  weight_decay: 0.01
  epochs: 10
  grad_clip: 1.0
  grad_accum_steps: 4

logging:
  log_every: 5
  log_path: "./uniphy/align_logs"
  ckpt_dir: "./uniphy/align_ckpt"
  use_wandb: true
  wandb_project: "ERA5-Align"
  wandb_entity: "UniPhy"
  wandb_run_name: "align_rollout_k2"

