model:
  in_channels: 30
  out_channels: 30
  embed_dim: 512
  expand: 4
  num_experts: 8
  depth: 8
  patch_size: 32
  img_height: 721
  img_width: 1440
  dt_ref: 6.0
  sde_mode: "det"
  init_noise_scale: 0.0
  max_growth_rate: 0.3

data:
  input_dir: "/nfs/ERA5_data/data_norm"
  test_year_range: [2022, 2022]
  input_steps: 1
  pred_steps: 8
  dt_ref: 6.0

inference:
  ckpt: "./uniphy/ckpt/ckpt_final.pt"
  batch_size: 1
  ensemble_size: 1
  dt_comparison: true 
  