model:
  in_channels: 30
  out_channels: 30
  embed_dim: 512
  expand: 4
  num_experts: 8
  depth: 8
  patch_size: 32
  img_height: 721
  img_width: 1440
  dt_ref: 6.0
  sde_mode: "sde"
  init_noise_scale: 1.0
  max_growth_rate: 0.3

inference:
  ckpt_path: "./uniphy/ckpt/ckpt_epoch13.pt"
  data_root: "/nfs/ERA5_data/data_norm"
  save_dir: "./uniphy/results"
  max_vis_samples: 5
  batch_size: 1
  year_range: [2021, 2021]
  cond_frames: 4
  pred_frames: 8
  dt_ref: 6.0
  num_ensemble: 3
  eval_sample_num: 100
  device: "cuda"
  use_tf32: true
  