data:
  input_dir: "/nfs/UniPhy/Data/ERA5"
  test_year_range: [2020, 2020]
  dt_ref: 1.0

inference:
  ckpt: "checkpoints/ckpt_final.pt"
  batch_size: 1
  max_samples: 5
  output_dir: "results_viz"
  ensemble_mode: true
  ensemble_size: 10
  input_len: 8
  input_dt: 6.0
  forecast_horizon: 12.0
  strategies:
    - {name: "dt=6.0", dt: 6.0}
    - {name: "dt=1.0", dt: 1.0}
    