model:
  in_channels: 30
  out_channels: 30
  embed_dim: 768
  expand: 4
  num_experts: 8
  depth: 12
  patch_size: 32
  img_height: 721
  img_width: 1440

data:
  input_dir: "/nfs/ERA5_data/data_norm"
  year_range: [2000, 2021]
  window_size: 24
  sample_k: 8
  look_ahead: 2
  dt_ref: 6.0

train:
  batch_size: 1
  lr: 3.0e-5
  weight_decay: 0.05
  epochs: 100
  grad_clip: 1.0
  grad_accum_steps: 1
  ensemble_size: 2
  use_scheduler: false
  use_tf32: true
  use_amp: true
  use_compile: false

logging:
  log_every: 1
  wandb_every: 1
  ckpt_step: 0.5
  log_path: "./uniphy/logs"
  ckpt_dir: "./uniphy/ckpt"
  ckpt: ""
  use_wandb: true
  wandb_project: "ERA5"
  wandb_entity: "UniPhy"
  wandb_run_name: ""
