model:
  in_channels: 30
  out_channels: 30
  embed_dim: 512
  expand: 4
  depth: 8
  patch_size: [7, 15]
  img_height: 721
  img_width: 1440
  dt_ref: 6.0
  sde_mode: "sde"
  init_noise_scale: 0.0001
  max_growth_rate: 0.3
  ensemble_size: 4

data:
  input_dir: "/nfs/ERA5_data/data_norm"
  year_range: [1979, 2015]
  window_size: 1
  sampling_mode: "mix"

train:
  batch_size: 4
  lr: 5.0e-4
  weight_decay: 0.01
  epochs: 100
  grad_clip: 1.0
  grad_accum_steps: 1

logging:
  log_every: 10
  log_path: "./uniphy/logs"
  ckpt_dir: "./uniphy/ckpt"
  use_wandb: true
  wandb_project: "ERA5-"
  wandb_entity: "UniPhy"
  wandb_run_name: ""

