model:
  in_channels: 30
  out_channels: 30
  embed_dim: 128
  expand: 4
  depth: 8
  patch_size: [7, 15]
  img_height: 721
  img_width: 1440
  dt_ref: 6.0
  tau_ref_hours: 6.0
  sde_mode: sde
  init_noise_scale: 0.0001
  max_growth_rate: 0.3
  ensemble_size: 8

data:
  input_dir: /nfs/ERA5_data/data_norm
  year_range: [2000, 2021]
  window_size: 10
  sample_k: 5
  look_ahead: 2
  sampling_mode: mix
  frame_hours: 6.0

train:
  seed: 1017
  num_workers: 4
  batch_size: 1
  lr: 1.0e-5
  weight_decay: 0.05
  epochs: 256
  grad_clip: 16.0
  grad_accum_steps: 1
  use_scheduler: false
  use_tf32: true

logging:
  log_every: 1
  wandb_every: 1
  ckpt_step: 0.5
  log_path: ./uniphy/logs
  ckpt_dir: ./uniphy/ckpt
  ckpt: ""
  use_wandb: true
  wandb_project: ERA5
  wandb_entity: UniPhy
  wandb_run_name: ""
